name: NodeJS with Webpack

on:
  push:
    branches: [ feature/mix ]
  pull_request:
    branches: [ feature/mix ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm install
    - name: Build
      run: node scripts/build.js
